---

- name: Prepare docker storage
  hosts: nodes:!masters
  roles:
    - setup-docker-storage

- name: Host Preparation
  hosts: nodes:!masters
  vars:
    volume_var_lib_origin: /var/lib/origin
    volume_var_log: /var/log
  roles:
     - host-preparation

