---

- name: Prepare docker storage
  hosts: masters
  roles:
    - setup-docker-storage

- name: Master Preparation
  hosts: masters
  vars:
    volume_var_lib_etcd: /var/lib/etcd
    volume_var_log: /var/log
  roles:
     - master-preparation

