---
- name: Setup Bastion Host
  hosts: localhost
  roles:
    - setup-bastion

# Note: Set bmo_run_prerequisite to 'True' for the initial cluster installation. Do NOT run the playbook for the subsequent run as it is not idemponent.
- import_playbook: host-preparation.yml
  when: bmo_run_prerequisite

- import_playbook: master-preparation.yml
  when: bmo_run_prerequisite

- name: Run OpenShift Pre Requisite playbook
  import_playbook: /usr/share/ansible/openshift-ansible/playbooks/prerequisites.yml
  when: bmo_run_prerequisite

- import_playbook: /usr/share/ansible/openshift-ansible/playbooks/deploy_cluster.yml openshift_metrics_install_metrics='False'

# Note: Run openshift-metrics playbook only during first installation. It needs to be installed after deploying OCS by the deploy_cluster playbook above.
- import_playbook: metrics-installation.yml
  when: bmo_run_prerequisite

- name: Run OpenShift Applier for Post Install tasks
  hosts: seed-hosts[0]
  roles:
    - openshift-applier

#- name: Post Installation
#  hosts: masters[0]
#  roles:
#    - post-install
