---
# tasks file for Host Preparation


- name: Check disk for Docker
  block:
    - name: get device name
      set_fact:
        device_name: "{{ item.key }}"
      no_log: True
      with_dict: "{{ ansible_devices }}"
      changed_when: false

    - name: show all values for selected device name
      debug: var=ansible_devices["{{ docker_disk }}"]["partitions"]

    - name: Fail if Disk is not available
      fail:
      when: ansible_devices[docker_disk] is not defined

    - name: Fail if Disk is Partitioned
      fail:
      when: ansible_devices[docker_disk]["partitions"] | length != 0

    - name: get lvm name
      set_fact:
        device_name: "{{ item.key }}"
      no_log: True
      with_dict: "{{ ansible_lvm }}"
      changed_when: false

    - name: show all values for selected pv name
      debug: var=ansible_lvm["pvs"]["{{ docker_device }}"]


    - name: Fail if "PVS" is configured
      fail:
      when: ansible_lvm["pvs"][docker_device] is defined


- name: Host preparation
  block:
    - name: Set SELinux to targeted if required
      selinux:
        policy: targeted
        state: enforcing

    - name: Extend varloglv LV to 20GB
      lvol:
        vg: rootvg
        lv: varloglv
        size: 20g
        shrink: no

    - name: Set ipv4.ip_forward to 1
      shell: "sed -i 's/net.ipv4.ip_forward = 0/net.ipv4.ip_forward = 1/g' /etc/sysctl.conf; sysctl -p"
      register: sysctl
    - debug: var=sysctl.stdout_lines

    - name: Copy Artifactory Certificates
      synchronize:
        src: {{ artifactory_cert_path }}
        dest: /etc/pki/ca-trust/source/anchors/
        use_ssh_args: yes
    - name: Update CA Trust
      command: /usr/bin/update-ca-trust extract


