---
# tasks file for Docker Storage Setup

- name: Check whether this already ran
  stat:
    path: /root/setup-docker-storage.stat
  register: stat_result

- name: Get disk for Docker
  block:
    - name: Get Docker Device Info
      set_fact:
        docker_device: "{{ hostvars[item]['container_runtime_docker_storage_setup_device'] }}"
      with_items: "{{ groups['new_nodes'] }}"

    - debug: msg="{{ docker_device }}"

    - name: Get Docker Disk Info
      set_fact:
        docker_disk: "{{ docker_device |replace(\"/dev/\",\"\") }}"

    - debug: msg="{{ docker_disk }}"

    
- name: Configure Docker Storage
  block:
    - name: Install docker
      yum:
        name: "{{ packages }}"
        state: present
      vars:
        packages:
        - docker-1.13*

    - name: Prepare /etc/sysconfig/docker-storage-setup
      blockinfile:
        path: /etc/sysconfig/docker-storage-setup
        block: |
          DEVS="{{ docker_device }}"
          VG=docker_vg
          DATA_SIZE=99%VG
          STORAGE_DRIVER="overlay2"
          CONTAINER_ROOT_LV_NAME="docker-root-lv"
          CONTAINER_ROOT_LV_SIZE="100%FREE"
          CONTAINER_ROOT_LV_MOUNT_PATH="/var/lib/docker"
          EXTRA_STORAGE_OPTIONS="--storage-opt overlay2.override_kernel_check=true --storage-opt overlay2.size=40G --graph=/var/lib/docker"

    - name: Stop docker service
      service:
        name: docker
        state: stopped

    - name: Create an empty directory (locally)
      local_action:
        module: file
        state: directory
        path: "/tmp/empty"

    - name: Empty /var/lib/docker
      synchronize:
        src: /tmp/empty/
        dest: /var/lib/docker
        delete: yes
        recursive: yes

    - name: Empty /etc/sysconfig/docker-storage file
      shell: echo /dev/null > /etc/sysconfig/docker-storage

    - name: Run docker-storage-setup
      shell: docker-storage-setup

    - name: Start docker service
      service:
        name: docker
        state: restarted

  when: stat_result.stat.exists == False


- name: Mark that this playbook ran
  copy:
    dest: "/root/setup-docker-storage.stat"
    content: |
      1
