---
# tasks file for roles/post install tasks

- name: Check openshift version
  shell: "export KUBECONFIG=/etc/origin/master/admin.kubeconfig; oc login -u system:admin >/dev/null; oc version | grep openshift"
  register: ocoutput
- debug: var=ocoutput.stdout_lines

- name: Check openshift version
  shell: "export KUBECONFIG=/etc/origin/master/admin.kubeconfig; oc login -u system:admin >/dev/null; oc delete pod -l logging-infra=fluentd --wait=false -n openshift-logging"
  register: ocoutput
- debug: var=ocoutput.stdout_lines
